const newH1 = document.querySelector('h1');
newH1.innerText = 'DOM Practice'
newH1.style.color = 'blue'
newH1.style.fontSize = '48px'
const newP = document.querySelector('p')
newP.innerText = 'I am learning DOM manipulation guysss!'
newP.style.color = 'green'
newP.style.fontSize = '25px'
newP.style.backgroundColor = 'lightgrey'
newP.style.borderRadius = '10px'
newP.style.padding = '15px'
